### ISSUE TITLE
ImportError - Mars5TTS

### ISSUE THREAD

**Issue by josiahbryan** [Camb-ai/MARS5-TTS#21]
I followed the QuickStart (https://github.com/Camb-ai/MARS5-TTS?tab=readme-ov-file#quickstart) and copy/pasted code exactly. (did the `pip install --upgrade torch torchaudio librosa vocos encodec`, etc) - and here's my script. But when I run it, it closes with error (full console log below the script):
```
ImportError: cannot import name 'Mars5TTS' from partially initialized module 'inference' (most likely due to a circular import) (/Users/josiahbryan/.cache/torch/hub/Camb-ai_mars5-tts_master/inference.py)
```

***Script (`mars5.py`):***
```python
import torch, librosa

mars5, config_class = torch.hub.load('Camb-ai/mars5-tts', 'mars5_english', trust_repo=True)
# The `mars5` contains the AR and NAR model, as well as inference code.
# The `config_class` contains tunable inference config settings like temperature.

# Load reference audio between 1-12 seconds.
wav, sr = librosa.load('/Users/josiahbryan/Downloads/fakePhoneConvoJosiah.wav',
                       sr=mars5.sr, mono=True)
wav = torch.from_numpy(wav)
ref_transcript = "Hey yeah okay...ummm, That sounds great. . Next, we're going to go, and, an' take it, yeah. Okay! Sounds good...when are you coming home? Perfect, okay, talk soon! Thanks, bye."

# Pick whether you want a deep or shallow clone. Set to False if you don't know prompt transcript or want fast inference. Set to True if you know transcript and want highest quality.
deep_clone = True
# Below you can tune other inference settings, like top_k, temperature, top_p, etc...
cfg = config_class(deep_clone=deep_clone, rep_penalty_window=100,
                      top_k=100, temperature=0.7, freq_penalty=3)

ar_codes, output_audio = mars5.tts("The quick brown rat.", wav,
          ref_transcript,
          cfg=cfg)
# output_audio is (T,) shape float tensor corresponding to the 24kHz output audio.
```

***Console Output:***
```bash
(base) josiahbryan@JosiahscBookPro devel % python mars5.py 
Downloading: "https://github.com/Camb-ai/mars5-tts/zipball/master" to /Users/josiahbryan/.cache/torch/hub/master.zip
Using cache found in /Users/josiahbryan/.cache/torch/hub/Camb-ai_mars5-tts_master
Traceback (most recent call last):
  File "/Users/josiahbryan/devel/rubber/backend/devel/mars5.py", line 3, in <module>
    mars5, config_class = torch.hub.load('Camb-ai/mars5-tts', 'mars5_english', trust_repo=True)
  File "/Users/josiahbryan/miniforge3/lib/python3.10/site-packages/torch/hub.py", line 568, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/Users/josiahbryan/miniforge3/lib/python3.10/site-packages/torch/hub.py", line 594, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "/Users/josiahbryan/miniforge3/lib/python3.10/site-packages/torch/hub.py", line 106, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/josiahbryan/.cache/torch/hub/Camb-ai_mars5-tts_master/hubconf.py", line 7, in <module>
    from inference import Mars5TTS, InferenceConfig
  File "/Users/josiahbryan/.cache/torch/hub/Camb-ai_mars5-tts_master/inference.py", line 12, in <module>
    from mars5.model import CodecLM, ResidualTransformer
  File "/Users/josiahbryan/devel/rubber/backend/devel/mars5.py", line 3, in <module>
    mars5, config_class = torch.hub.load('Camb-ai/mars5-tts', 'mars5_english', trust_repo=True)
  File "/Users/josiahbryan/miniforge3/lib/python3.10/site-packages/torch/hub.py", line 568, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/Users/josiahbryan/miniforge3/lib/python3.10/site-packages/torch/hub.py", line 594, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "/Users/josiahbryan/miniforge3/lib/python3.10/site-packages/torch/hub.py", line 106, in _import_module
    spec.loader.exec_module(module)
  File "/Users/josiahbryan/.cache/torch/hub/Camb-ai_mars5-tts_master/hubconf.py", line 7, in <module>
    from inference import Mars5TTS, InferenceConfig
ImportError: cannot import name 'Mars5TTS' from partially initialized module 'inference' (most likely due to a circular import) (/Users/josiahbryan/.cache/torch/hub/Camb-ai_mars5-tts_master/inference.py)
```

**Comment by arnavmehta7** [comment]
Hey, please check the [notebook ](https://github.com/Camb-ai/MARS5-TTS/blob/master/mars5_demo.ipynb)
you can load the model by:
```py
import torch
# load model
mars5, config_class = torch.hub.load('Camb-ai/mars5-tts', 'mars5_english', trust_repo=True)
```

**Comment by josiahbryan** [comment]
I will happily try that tomorrow. Please do keep in mind, the code that I
was using was copied straight from the readme. Are you saying that the
quick start there needs changed as well?

**Comment by josiahbryan** [comment]
@arnavmehta7 I literally copied-pasted the import from the notebook -same error. Tried copy/pasting your code, same error. No clue what's going on here - I don't write a lot of python, so not used to reading the stack traces, but it SEEMS a problem in the package published on torch.hub because the error seems to happen inside `.cache/torch/hub/Camb-ai_mars5-tts_master/inference.py`

So my test file is literally just:
```
import torch
mars5, config_class = torch.hub.load('Camb-ai/mars5-tts', 'mars5_english', trust_repo=True)
```
... and it gives the same error:
```
ImportError: cannot import name 'Mars5TTS' from partially initialized module 'inference' (most likely due to a circular import) (/Users/josiahbryan/.cache/torch/hub/Camb-ai_mars5-tts_master/inference.py)
```

So yeah, something still very broken. Any suggestions on how to fix?

**Comment by matus-pikuliak** [comment]
Try renaming the `mars5.py` file to something else. It shadows the name of the package so that might cause some issues.

**Comment by josiahbryan** [comment]
WOW - that was IT... reason number 1,024 on why I can't stand python lol. Consider issue closed. So stupid. (Python, not you)

**Comment by slx965** [comment]
How do I load the local model?
